###
POST http://localhost:5005/api/poesia/find
Content-Type: application/json

{
    "filters": [
        { 
            "key": "persona",
            "op": "==",
            "val": "munir"
        }
    ]
}

###
GET http://localhost:5005/api/persona/munir

###
POST http://localhost:5005/api/planeta/find
Content-Type: application/json

{
    "filters": [{ "key": "persona", "op": "==", "val": "apollo" }]
}